package withdrawal

import (
	"context"

	"mynance/internal/shared"
)

// Processor decides how POST /withdrawals is handled per environment. The
// real impl runs the full withdrawal pipeline and enforces an
// idempotency key from the caller. The sandbox impl auto-fills the key and
// applies the simulator's amount cap so the FE can replay flows without
// tracking keys.
type Processor interface {
	Withdraw(ctx context.Context, cmd WithdrawCommand) (*WithdrawResult, error)
}

type realProcessor struct {
	svc Service
}

// NewProcessor wires the production withdrawal path. The caller MUST
// supply an idempotency key — duplicate retries on flaky networks need a
// stable key to deduplicate against.
func NewProcessor(svc Service) Processor {
	return &realProcessor{svc: svc}
}

func (p *realProcessor) Withdraw(ctx context.Context, cmd WithdrawCommand) (*WithdrawResult, error) {
	if cmd.IdempotencyKey == "" {
		return nil, shared.ErrBadRequest
	}
	return p.svc.Withdraw(ctx, cmd)
}

type sandboxProcessor struct {
	svc Service
}

// NewSandboxProcessor wires the sandbox withdrawal path. Idempotency key is
// auto-generated by Simulate so the FE can stay key-less while still going
// through the real ledger debit + outbox emission.
func NewSandboxProcessor(svc Service) Processor {
	return &sandboxProcessor{svc: svc}
}

func (p *sandboxProcessor) Withdraw(ctx context.Context, cmd WithdrawCommand) (*WithdrawResult, error) {
	return p.svc.Simulate(ctx, cmd)
}
